version: '3.1'

services:
  redis:
    restart: on-failure
    image: redis:latest
    healthcheck:
      test: "redis-cli ping"
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  # db:
  #   image: postgres:latest
  #   restart: on-failure
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: example
